version: 2
updates:
- package-ecosystem: cargo
  directory: "/language-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: lsp-types
    versions:
    - 0.86.0
    - 0.87.0
    - 0.88.0
  - dependency-name: typed-builder
    versions:
    - 0.8.0
- package-ecosystem: cargo
  directory: "/language-server-macros"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
