[package]
name = "language-server-derive"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true
doctest = false

[dependencies]
darling = "0.10"
syn = "1.0"
quote = "1.0"
